In [1]:
import scipy as sp
import pandas as pd
import matplotlib.pyplot as plt
import statsmodels.formula.api as sm
import numpy as np


In [2]:
#x 1.0 1.25 1.5 1.75 2.0
#y 0.571 0.293 0.123 0.0427 0.0123
# funcao -> y = alpha *x^beta *e ^(-gama*x^(2))
Y = np.array([
    [np.log(0.293)],
    [np.log(0.123)],
    [np.log(0.0427)],
    ])
Y

array([[-1.22758267],
       [-2.09557092],
       [-3.15355636]])

In [3]:
Omega = np.array([
    [1, np.log(1.25), -1*np.exp(1.25)],
    [1, np.log(1.5),  -1*np.exp(1.5)],
    [1, np.log(1.75), -1*np.exp(1.75)],
    ])

Omega

array([[ 1.        ,  0.22314355, -3.49034296],
       [ 1.        ,  0.40546511, -4.48168907],
       [ 1.        ,  0.55961579, -5.75460268]])

In [4]:
OmegaInv = np.linalg.inv(Omega)
OmegaInv

array([[ -2.20447821,   8.44213922,  -5.23766102],
       [-16.05938462,  28.56644593, -12.50706131],
       [ -1.9448021 ,   4.24501477,  -2.30021267]])

In [5]:
X = np.linalg.solve(Omega, Y)
X

#OU 

X2 = OmegaInv @ Y
print(X)
print(X2)


[[ 1.53233696]
 [-0.7070685 ]
 [ 0.74552612]]
[[ 1.53233696]
 [-0.7070685 ]
 [ 0.74552612]]


In [10]:
alpha =  np.exp(X2[0][0])
beta = X2[1][0]
gama = X2[2][0]
print(alpha)
print(beta)
print(gama)

4.6289819312502445
-0.7070685002014545
0.7455261228428632
